### ISSUE TITLE
IOS  收到通知点击进去后 还显示一条通知在icon上面，badge 没有更新

### ISSUE THREAD

**Issue by BANG88** [KenChoi1992/react-native-jpush-plugin#3]
RT

**Comment by huangminlinux** [comment]
根据你的情况你需要在进入 应用的时候 改变 native 的值。
你可以在 iOS 工程中 的 appdelegate.m 文件，applicationWillEnterForeground方法中，添加如下代码
- (void)applicationWillEnterForeground:(UIApplication *)application {
  [[UIApplication sharedApplication] setApplicationIconBadgeNumber: 0]; // 要添加的方法   0 就是你要设置的badge
  }

**Comment by BANG88** [comment]
这个还是在README里面写一下吧，估计都有这个需求。或者js里面有方法设置这个badge的也可以
