### ISSUE TITLE
每次启动会导致Module RCTNativeAppEventEmitter is not a registered callable module错误

### ISSUE THREAD

**Issue by HADB** [KenChoi1992/react-native-jpush-plugin#5]
引入jpush plugin之后，每次重新启动ios app会导致一个错误：Module RCTNativeAppEventEmitter is not a registered callable module，ReloadJS之后可正常使用。

**Comment by KenChoi1992** [comment]
@HADB 请转到我们的官方库： [jpush-react-native](https://github.com/jpush/jpush-react-native)，这个库此前建来测试用的。
